package by.htp.ts.command;

public enum CommandName {
	AUTHORIZATION, REGISTRATION, LOGOUT,
	
	SAVE_TEST_NAME_AND_DURATION,
	GO_TO_MARK_RIGHT_ANSWERS_PAGE, GO_TO_QUESTION_ADD_PAGE,
	SAVE_TEST, QUESTION_SAVE, GO_TO_ADD_Q_SAVE_T_PAGE,
	CREATED_TESTS, EDIT_TEST,
	GO_TO_CREATED_TESTS_PAGE, GO_TO_TEST_LIST_PAGE,
	GO_TO_TEST_EDITION_PAGE, TEST_EDITION,
	TEST_LIST, START_TEST, GO_TO_START_TEST_PAGE,
	FINISH_TEST, GO_TO_TEST_RESULT_PAGE,
	PROGRESS, DELETE_TEST, GO_TO_SOME_PAGE,
	GO_TO_TEST_CREATION_PAGE,
	
	GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE,
	GO_TO_MAIN_PAGE, GO_TO_ERROR_PAGE,
	
	GO_TO_TESTCREATION_PAGE,
	
	CHANGE_LANGUAGE
}
